/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taxi.modele;
import myconnnections.DBConnection;
import java.awt.CardLayout;
import java.sql.Connection;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import taxi.metier.API_ADRESSE1;
import taxi.metier.API_CLIENT1;
import taxi.metier.API_LOCATION1;
import taxi.metier.API_TAXI1;
import taxi.DAO.ClientDAO;
import taxi.DAO.API_TAXI1DAO;
import taxi.DAO.ClientDAO;
import taxi.DAO.API_TAXI1DAO;
import taxi.DAO.API_LOCATION1DAO;
import taxi.DAO.AdresseDAO;

/**
 *
 * @author CASHCONVERTERS
 */
public class CreerLoc extends javax.swing.JPanel {

    /**
     * Creates new form CreerLoc
     */
    ClientDAO clientDAO = null;
    AdresseDAO adresseDAO = null;
    API_LOCATION1DAO locationDAO = null;
    API_TAXI1DAO taxiDAO = null;
    DefaultComboBoxModel dcbmcli = new DefaultComboBoxModel();
    DefaultComboBoxModel dcbmtx = new DefaultComboBoxModel();
    DefaultComboBoxModel dcbmdep = new DefaultComboBoxModel();
    DefaultComboBoxModel dcbmarr = new DefaultComboBoxModel();
    List<API_ADRESSE1> dep;
    List<API_ADRESSE1> arr;
    List<API_TAXI1> tx;
    List<API_CLIENT1> cli;
    
    public CreerLoc() {
        initComponents();
    }

    public void setLocationDAO(API_LOCATION1DAO locationDAO) {
        this.locationDAO = locationDAO;
    }
     public void setAdresseDAO(AdresseDAO adresseDAO) {
        this.adresseDAO = adresseDAO;
    }
     
    public void setTaxiDAO(API_TAXI1DAO taxiDAO) {
        this.taxiDAO = taxiDAO;
    }

    public void setClientDAO(ClientDAO clientDAO) {
        this.clientDAO = clientDAO;
    }
    
    public void AddClient() {
        try {
            cli = clientDAO.Affiche();
            if (client != null) {
                client.removeAllItems();
            }

            Iterator<API_CLIENT1> itc = cli.iterator();
            while (itc.hasNext()) {
                API_CLIENT1 cl = itc.next();
                dcbmcli.addElement(cl.toString());
            }
           
            client.setModel(dcbmcli);

        } catch (SQLException e) {
            System.out.println("Exception" + e);
        }
    }
    
     public void AddAddress() {
        try {
            dep = adresseDAO.affiche();
            arr = adresseDAO.affiche();
            if (depart != null) {
                depart.removeAllItems();
                arrive.removeAllItems();
            }

            Iterator<API_ADRESSE1> itad1 = dep.iterator();
            Iterator<API_ADRESSE1> itad2 = arr.iterator();

            while (itad1.hasNext()) {
                API_ADRESSE1 ad1 = itad1.next();
                API_ADRESSE1 ad2 = itad2.next();
                dcbmdep.addElement(ad1.toString());
                dcbmarr.addElement(ad2.toString());

            }
            depart.setModel(dcbmdep);
            arrive.setModel(dcbmarr);

        } catch (SQLException e) {
            System.out.println("Exception" + e);
        }
    }
       public void Addtaxi() {
        try {
            tx = taxiDAO.Affiche();
            if (taxi != null) {
                taxi.removeAllItems();
            }
            Iterator<API_TAXI1> ittx = tx.iterator();
            while (ittx.hasNext()) {
                API_TAXI1 v = ittx.next();
                dcbmtx.addElement(v.toString());
            }
           
            taxi.setModel(dcbmtx);

        } catch (SQLException e) {
            System.out.println("Exception" + e);
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        client = new javax.swing.JComboBox<>();
        taxi = new javax.swing.JComboBox<>();
        depart = new javax.swing.JComboBox<>();
        arrive = new javax.swing.JComboBox<>();
        km = new javax.swing.JTextField();
        acompte = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        date = new javax.swing.JFormattedTextField();
        valider = new javax.swing.JButton();

        jFormattedTextField2.setText("jFormattedTextField2");

        setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 3, 24)); // NOI18N
        jLabel1.setText("Auto Rent");

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel2.setText("Client");

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel3.setText("Taxi");

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel4.setText("Départ");

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel5.setText("Arrivée");

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel6.setText("Km");

        jLabel7.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel7.setText("Acompte");

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel8.setText("Total");

        jLabel9.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        jLabel9.setText("Date");

        client.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientActionPerformed(evt);
            }
        });

        taxi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        depart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        arrive.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        acompte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acompteActionPerformed(evt);
            }
        });

        date.setText("    /        /");

        valider.setFont(new java.awt.Font("Lucida Handwriting", 1, 12)); // NOI18N
        valider.setText("Ajouter");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(client, 0, 116, Short.MAX_VALUE)
                                .addComponent(taxi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(depart, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(arrive, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(km)
                                .addComponent(acompte)
                                .addComponent(total))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(valider))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(taxi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(depart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(arrive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(km, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(acompte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(valider)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
        try {

            String dtdeb = date.getText();
            int jdeb = Integer.parseInt(dtdeb.substring(0, 2));
            int mdeb = Integer.parseInt(dtdeb.substring(3, 5));
            int adeb = Integer.parseInt(dtdeb.substring(6));

            LocalDate day = LocalDate.of(adeb, mdeb, jdeb);

            int kmtotal = Integer.parseInt(km.getText());
            Float acomptes = Float.parseFloat(acompte.getText());
            Float totals = Float.parseFloat(total.getText());
            int fkclient = client.getSelectedIndex();
            API_CLIENT1 client2 = cli.get(fkclient);
            int fktx = taxi.getSelectedIndex();
            API_TAXI1 tx1 = tx.get(fktx);
            int fkdeb = depart.getSelectedIndex();
            API_ADRESSE1 addresst = dep.get(fkdeb);
            int fkarr = arrive.getSelectedIndex();
            API_ADRESSE1 addressend = arr.get(fkarr);
            //API_LOCATION1(idloc, dateloc, kmtotal, acompte, total, id_deb, id_fin,  idtaxi, idclient
            API_LOCATION1 l = new API_LOCATION1(0, day, kmtotal, acomptes, totals, addresst.getIdadr(), addressend.getIdadr(), tx1.getIdtaxi(),client2.getIdclient());
            locationDAO.create(l);
            AddAddress();
            Addtaxi();
            AddClient();
            JOptionPane.showMessageDialog(this, "Location créé", "Succès", JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (HeadlessException | NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(CreerLoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_validerActionPerformed

    private void acompteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acompteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acompteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acompte;
    private javax.swing.JComboBox<String> arrive;
    private javax.swing.JComboBox<String> client;
    private javax.swing.JFormattedTextField date;
    private javax.swing.JComboBox<String> depart;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField km;
    private javax.swing.JComboBox<String> taxi;
    private javax.swing.JTextField total;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
